#!/bin/sh
#
# Start the aesdsocket....
#

case "$1" in
  start)
    echo "Starting aesdsocket..."
    start-stop-daemon -S /usr/bin/aesdsocket -d
    ;;

  stop)
    echo "Stopping aesdsocket..."
    start-stop-daemon -K aesdsocket
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0